---
- name: Place backend code in Server
  become: true
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/
    owner: ubuntu

# - name: Place package file in Server
#   become: true
#   copy:
#     src: /root/project/backend/package.json
#     dest: /home/ubuntu/
#     owner: ubuntu

- name: Install dependencies
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: Build Backend
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: Run server
  become: true
  shell: |
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}"
    export TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}"
    cd /home/ubuntu/backend
    ls
    pm2 start npm -- run start