---
- name: Check files
  shell: |
    cd /root/project/backend/dist
    ls

- name: Place backend code in Server
  become: true
  copy:
    src: /root/project/backend/dist
    dest: /home/ubuntu/
    force: yes

- name: Place packageJson in Server
  become: true
  copy:
    src: /root/project/backend/package.json
    dest: /home/ubuntu/

- name: Install dependencies
  shell: |
    cd /home/ubuntu
    ls
    npm install

# - name: Build Backend
#   become: true
#   shell: |
#     cd /home/ubuntu/backend
#     npm run build

- name: Run server
  become: true
  shell: |
    ls
    cd /home/ubuntu/dist
    ls
    pm2 start npm -- run start